# Supabase configuration file
# https://supabase.com/docs/guides/cli/config

# Disable JWT verification for Stripe webhook
[functions.stripe-webhook]
verify_jwt = false

# Disable JWT verification for subscription management functions
# These functions handle JWT manually for better error handling
[functions.cancel-subscription]
verify_jwt = false

[functions.reactivate-subscription]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.stripe-redirect]
verify_jwt = false

# Disable JWT verification for payment functions
# These functions handle JWT manually for better error handling
[functions.create-payment-intent]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.capture-deposit]
verify_jwt = false

[functions.capture-remaining-payment]
verify_jwt = false